In [34]:
from aeon.datasets import load_classification
X,Y = load_classification("StandWalkJump")
print(X)
print(Y)
print(X.shape)
print(Y.shape)
print(type(Y))
new_x = X.transpose(0,2,1)
print(new_x.shape)

[[[-0.28 -0.28 -0.27 ... -0.03 -0.04 -0.04]
  [-0.11 -0.11 -0.11 ...  0.06  0.06  0.08]
  [ 0.41  0.42  0.43 ... -0.01  0.    0.03]
  [ 0.59  0.59  0.58 ...  0.04  0.04  0.03]]

 [[-0.13 -0.1  -0.09 ... -0.13 -0.16 -0.18]
  [-0.09 -0.09 -0.07 ... -0.05 -0.08 -0.12]
  [ 0.05  0.08  0.11 ... -0.14 -0.15 -0.15]
  [-0.15 -0.09 -0.07 ... -0.1  -0.1  -0.04]]

 [[-0.01 -0.01 -0.02 ...  0.    0.    0.  ]
  [ 0.13  0.13  0.15 ...  0.04  0.03  0.05]
  [-0.11 -0.1  -0.11 ... -0.13 -0.13 -0.13]
  [-0.07 -0.06 -0.07 ... -0.19 -0.17 -0.17]]

 ...

 [[ 0.2   0.21  0.24 ... -0.71 -0.74 -0.77]
  [-0.01  0.    0.   ...  1.04  1.08  1.06]
  [-0.22 -0.22 -0.23 ...  1.66  1.72  1.7 ]
  [ 0.4   0.42  0.41 ... -1.39 -1.43 -1.44]]

 [[ 0.37  0.39  0.4  ... -0.07 -0.09 -0.1 ]
  [-0.05 -0.04 -0.04 ... -0.13 -0.14 -0.15]
  [-0.58 -0.57 -0.58 ...  0.01  0.    0.01]
  [-0.6  -0.61 -0.64 ...  0.17  0.17  0.18]]

 [[-0.17 -0.17 -0.17 ... -0.33 -0.33 -0.32]
  [ 0.13  0.19  0.22 ... -2.51 -2.47 -2.41]
  [-0.15 -0.19 -

In [39]:
import numpy as np

# 示例数据
X = np.random.rand(100, 5, 4)  # 假设 X 是一个形状为 (100, 5, 4) 的三维数组
Y = np.random.randint(0, 10, 100)  # 假设标签范围在 0 到 9 之间
print(X.shape)
print(Y.shape)
N = 1
# 获取每种标签的索引
unique_labels, label_counts = np.unique(Y, return_counts=True)

# 初始化用于存储的容器
X_part1 = []
Y_part1 = []
X_part2 = []
Y_part2 = []

# 分别对每种标签进行处理
for label in unique_labels:
    # 获取当前标签的索引
    indices = np.where(Y == label)[0]
    
    # 随机挑选 N 个样本
    selected_indices = np.random.choice(indices, N, replace=False)
    
    # 将这些样本分配给第一部分，其余分配给第二部分
    X_part1.extend(X[selected_indices])
    Y_part1.extend(Y[selected_indices])
    X_part2.extend(X[np.setdiff1d(indices, selected_indices)])
    Y_part2.extend(Y[np.setdiff1d(indices, selected_indices)])

# 转换为 NumPy 数组
X_part1 = np.array(X_part1)
Y_part1 = np.array(Y_part1)
X_part2 = np.array(X_part2)
Y_part2 = np.array(Y_part2)

print("第一部分数据:")
print("X_part1 shape:", X_part1.shape)
print("Y_part1 shape:", Y_part1.shape)

print("\n第二部分数据:")
print("X_part2 shape:", X_part2.shape)
print("Y_part2 shape:", Y_part2.shape)
print(Y_part1)


(100, 5, 4)
(100,)
第一部分数据:
X_part1 shape: (10, 5, 4)
Y_part1 shape: (10,)

第二部分数据:
X_part2 shape: (90, 5, 4)
Y_part2 shape: (90,)
[0 1 2 3 4 5 6 7 8 9]
